import settings from 'carbon-components/es/globals/js/settings';
import { html, property, customElement, LitElement } from 'lit-element';
import styles from './dropdown.scss';

const { prefix } = settings;

/**
 * Dropdown menu item.
 */
@customElement(`${prefix}-dropdown-item` as any)
class BXDropdownItem extends LitElement {
  /**
   * The link href of the dropdown item. Corresponds to the attribute with the same name.
   */
  @property()
  href = '';

  /**
   * The value of the dropdown item. Corresponds to the attribute with the same name.
   */
  @property()
  value = '';

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'option');
    }
    super.connectedCallback();
  }

  render() {
    /* eslint-disable no-script-url */
    return html`
      <a href=${this.href || 'javascript:void 0'} class=${`${prefix}--dropdown-link`}><slot></slot></a>
    `;
    /* eslint-enable no-script-url */
  }

  /**
   * The CSS class for the selected item.
   */
  static classSelected = `${prefix}--dropdown--selected`;

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXDropdownItem;
