/**
 * @license
 *
 * Copyright IBM Corp. 2019
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import { classMap } from 'lit-html/directives/class-map';
import settings from 'carbon-components/es/globals/js/settings';
import TAG_TYPE from './types';
import styles from './tag.scss';

export { TAG_TYPE };

const { prefix } = settings;

/**
 * Tag.
 */
@customElement(`${prefix}-tag`)
export default class BXTag extends LitElement {
  /**
   * `true` if the tag should be disabled
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * Specify the type of the <Tag>
   */
  @property({ reflect: true })
  type = TAG_TYPE.RED;

  render() {
    const { disabled, type } = this;
    const classes = classMap({
      [`${prefix}--tag`]: true,
      [`${prefix}--tag--${type}`]: true,
      [`${prefix}--tag--disabled`]: disabled,
    });
    return html`
      <span class="${classes}">
        <slot></slot>
      </span>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}
