import settings from 'carbon-components/es/globals/js/settings';
import { customElement, LitElement, html, property } from 'lit-element';
import styles from './input.scss';

const { prefix } = settings;

@customElement(`${prefix}-input`)
export default class BXInput extends LitElement {
  @property()
  placeholder = '';

  @property()
  value = '';

  @property()
  type = 'text';

  @property({ type: Boolean })
  disabled = false;

  render() {
    return html`
      <input
        class="bx--text-input"
        ?disabled="${this.disabled}"
        type="${this.type}"
        value="${this.value}"
        placeholder="${this.placeholder}"
      />
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}
