import settings from 'carbon-components/es/globals/js/settings';
import { customElement, LitElement, html, property } from 'lit-element';
import classnames from 'classnames';
import styles from './form-item.scss';

const { prefix } = settings;

@customElement(`${prefix}-form-item`)
export default class BXFormItem extends LitElement {
  @property({ type: Boolean })
  invalid = false;

  /**
   * Unique ID used for ID refs.
   */
  protected _uniqueInputId = Math.random()
    .toString(36)
    .slice(2);

  render() {
    const formControl = this.querySelector('*:not([slot])');
    if (formControl) {
      formControl.setAttribute('id', this._uniqueInputId);
      if (this.invalid) {
        formControl.setAttribute('invalid', '');
      } else {
        formControl.removeAttribute('invalid');
      }
    }
    const formItemClasses = classnames('bx--form-item', {
      'bx-ce--invalid': this.invalid,
    });
    return html`
      <div class="${formItemClasses}">
        <label class="bx--label" for="${this._uniqueInputId}"><slot name="label"></slot></label>
        <div class="bx--form__helper-text"><slot name="help-text"></slot></div>
        <slot></slot>
        <div class="bx--form-requirement"><slot name="validation"></slot></div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader

  static formAssociated = true;
}
