import settings from 'carbon-components/es/globals/js/settings';
import { customElement, LitElement, html } from 'lit-element';
import styles from './form-item.scss';

const { prefix } = settings;

/**
 * Presentational element for form items
 */
@customElement(`${prefix}-form-item`)
export default class BXFormItem extends LitElement {
  render() {
    return html`
      <div class="bx--form-item">
        <slot></slot>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}
