import settings from 'carbon-components/es/globals/js/settings';
import { customElement, LitElement, html } from 'lit-element';
import styles from './form-item.scss';

const { prefix } = settings;

@customElement(`${prefix}-form-item`)
export default class BXFormItem extends LitElement {
  render() {
    return html`
      <div class="bx--form-item">
        <label class="bx--label"><slot name="label"></slot></label>
        <div class="bx--form__helper-text"><slot name="help-text"></slot></div>
        <slot></slot>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}
