import settings from 'carbon-components/es/globals/js/settings';
import { html, customElement, LitElement } from 'lit-element';
import styles from './focus-trap.scss';

const { prefix } = settings;

@customElement(`${prefix}-focus-trap` as any)
class BXFocusTrap extends LitElement {
  /**
   * A property that tells our a11y engine that this element is put off-screen and thus hidden.
   */
  PT_NODE_HIDDEN = true;

  createRenderRoot() {
    return this.attachShadow({ mode: 'open', delegatesFocus: true });
  }

  render() {
    return html`
      <input type="text" />
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXFocusTrap;
