import { svg } from 'lit-html';
import { unsafeHTML } from 'lit-html/directives/unsafe-html';

import { toString, getAttributes } from '@carbon/icon-helpers';

/**
 * Function that takes a valid @carbon/icons style icon descriptor and returns a lit-html svg instance
 * @param {object} descriptor Object representation of an SVG icon as generated by @carbon/icons
 * @param {object} attributes Optional. object representation of SVG attributes
 */
export const icon = (descriptor, attributes = {}) => {
  descriptor.attrs = getAttributes(Object.assign(descriptor.attrs, attributes));
  return svg`
    ${unsafeHTML(toString(descriptor))}
  `;
};

export default icon;
