import { html, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './modal.scss';

const { prefix } = settings;

/**
 * Modal close button.
 */
@customElement(`${prefix}-modal-close-button` as any)
class BXModalCloseButton extends LitElement {
  /**
   * A boolean value to indicate that this element is a modal close button.
   */
  isModalCloseButton = true;

  render() {
    return html`
      <style>
        ${styles}
      </style>
      <svg
        focusable="false"
        preserveAspectRatio="xMidYMid meet"
        aria-label="Close the modal"
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 32 32"
        role="img"
        class="bx--modal-close__icon"
        style="will-change: transform;"
      >
        <path d="M24 9.4L22.6 8 16 14.6 9.4 8 8 9.4l6.6 6.6L8 22.6 9.4 24l6.6-6.6 6.6 6.6 1.4-1.4-6.6-6.6L24 9.4z"></path>
      </svg>
    `;
  }

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'button');
    }
    super.connectedCallback();
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXModalCloseButton;
