import { html, customElement, LitElement } from 'lit-element';
import Close20 from '@carbon/icons/lib/close/20';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './modal.scss';

const { prefix } = settings;

/**
 * Modal close button.
 */
@customElement(`${prefix}-modal-close-button` as any)
class BXModalCloseButton extends LitElement {
  render() {
    return html`
      ${Close20({
        class: `${prefix}--modal-close__icon`,
      })}
    `;
  }

  connectedCallback() {
    if (!this.hasAttribute('tabindex')) {
      this.setAttribute('tabindex', '0');
    }
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'button');
    }
    super.connectedCallback();
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXModalCloseButton;
