/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import Close20 from '@carbon/icons/lib/close/20';
import settings from 'carbon-components/es/globals/js/settings';
import ifNonNull from '../../globals/directives/if-non-null';
import styles from './modal.scss';

const { prefix } = settings;

/**
 * Modal close button.
 * @element bx-modal-close-button
 */
@customElement(`${prefix}-modal-close-button`)
class BXModalCloseButton extends LitElement {
  /**
   * The assistive text for the button.
   */
  @property({ attribute: 'assistive-text' })
  assistiveText = 'Close';

  createRenderRoot() {
    return this.attachShadow({
      mode: 'open',
      delegatesFocus: Number((/Safari\/(\d+)/.exec(navigator.userAgent) ?? ['', 0])[1]) <= 537,
    });
  }

  render() {
    const { assistiveText } = this;
    return html`
      <button aria-label="${ifNonNull(assistiveText)}" class="${prefix}--modal-close" title="${ifNonNull(assistiveText)}">
        ${Close20({
          class: `${prefix}--modal-close__icon`,
        })}
      </button>
    `;
  }

  connectedCallback() {
    if (!this.hasAttribute('tabindex')) {
      this.setAttribute('tabindex', '0');
    }
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'button');
    }
    super.connectedCallback();
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXModalCloseButton;
