/**
 * @license
 *
 * Copyright IBM Corp. 2019
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import settings from 'carbon-components/es/globals/js/settings';
import classnames from 'classnames';
import { html, property, customElement, LitElement } from 'lit-element';
import styles from './side-nav.scss';

const { prefix } = settings;

/**
 * Side nav menu item.
 */
@customElement(`${prefix}-side-nav-menu-item`)
class BXSideNavMenuItem extends LitElement {
  /**
   * `true` if the menu item should be active. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true })
  active = false;

  /**
   * Link `href`. Corresponds to the attribute with the same name.
   */
  @property()
  href = '';

  render() {
    const { active, href } = this;
    const classes = classnames(`${prefix}--side-nav__link`, {
      [`${prefix}--side-nav__link--current`]: active,
    });
    return html`
      <a role="menuitem" class="${classes}" href="${href}">
        <span class="${prefix}--side-nav__link-text">
          <slot></slot>
        </span>
      </a>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXSideNavMenuItem;
