/**
 * @license
 *
 * Copyright IBM Corp. 2019
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import settings from 'carbon-components/es/globals/js/settings';
import { html, property, customElement, LitElement } from 'lit-element';
import styles from './side-nav.scss';

const { prefix } = settings;

/**
 * Side nav.
 */
@customElement(`${prefix}-side-nav`)
class BXSideNav extends LitElement {
  /**
   * `true` to expand the side nav. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true })
  expanded = false;

  /**
   * `true` to make the side nav non-collapsible. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true })
  fixed = false;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'navigation');
    }
    super.connectedCallback();
  }

  render() {
    return html`
      <slot></slot>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXSideNav;
