import classnames from 'classnames';
import { html, property, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './checkbox.scss';

const { prefix } = settings;

/**
 * Check box.
 */
@customElement(`${prefix}-checkbox` as any)
class BXCheckbox extends LitElement {
  /**
   * Unique ID used for ID refs.
   */
  protected _uniqueId = Math.random()
    .toString(36)
    .slice(2);

  /**
   * Handles `click` event on the `<input>` in the shadow DOM.
   */
  protected _handleChange() {
    const { id: elementId } = this;
    const { checked, indeterminate } = this.shadowRoot!.getElementById(
      `__bx-ce-checkbox_${elementId || this._uniqueId}`
    ) as HTMLInputElement;
    this.checked = checked;
    this.indeterminate = indeterminate;
  }

  /**
   * `true` if the check box should be checked. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true })
  checked = false;

  /**
   * `true` if the check box should be disabled. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  /**
   * `true` if the label should be hidden. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true, attribute: 'hide-label' })
  hideLabel = false;

  /**
   * `true` if the check box should show its UI of the indeterminate state. Corresponds to the attribute with the same name.
   */
  @property({ type: Boolean, reflect: true })
  indeterminate = false;

  /**
   * The label text. Corresponds to `label-text` attribute.
   */
  @property({ attribute: 'label-text' })
  labelText = '';

  /**
   * The value. Corresponds to the attribute with the same name.
   */
  @property({ type: String })
  value = '';

  createRenderRoot() {
    return this.attachShadow({ mode: 'open', delegatesFocus: true });
  }

  render() {
    const { id: elementId, checked, disabled, hideLabel, indeterminate, labelText, value, _handleChange: handleChange } = this;
    const labelClasses = classnames(`${prefix}--checkbox-label`, {
      [`${prefix}--visually-hidden`]: hideLabel,
    });
    const checkboxId = `__bx-ce-checkbox_${elementId || this._uniqueId}`;
    return html`
      <input
        id="${checkboxId}"
        type="checkbox"
        class="${`${prefix}--checkbox`}"
        aria-checked="${indeterminate ? 'mixed' : String(Boolean(checked))}"
        .checked=${checked}
        ?disabled=${disabled}
        .indeterminate=${indeterminate}
        .value="${value}"
        @change=${handleChange}
      />
      <label for="${checkboxId}" class="${labelClasses}">${labelText}</label>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXCheckbox;
