name: dependabot-yarn-mirror

on: [pull_request]

concurrency:
  group: dependabot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-offline-mirror:
    if: github.repository == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}
      - uses: fregante/setup-git-user@v1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch
      - name: Update yarn offline mirror
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: |
          yarn
          git add -A
          if [[ ! -z $(git status -s) ]] ; then
            git commit -m "chore(yarn): update yarn offline mirror"
            git push origin ${{ steps.get_branch.outputs.branch }}
          fi
