name: dependabot-yarn-mirror

on: [pull_request]

concurrency:
  group: dependabot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-offline-mirror:
    if: github.repository == github.event.pull_request.head.repo.full_name && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: yarn
      - name: Update yarn offline mirror
        run: |
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git config --global user.name ${{ secrets.BOT_NAME }}

          yarn
          git add -A
          if [[ ! -z $(git status -s) ]] ; then
            git commit -m "chore(yarn): update yarn offline mirror"
            git push origin ${{ github.head_ref }}
          fi
