name: dependabot-yarn-mirror

on: [pull_request]

concurrency:
  group: dependabot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-offline-mirror:
    if: github.repository == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Update yarn offline mirror
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: |
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git config --global user.name ${{ secrets.BOT_NAME }}
          git config --global github.token ${{ secrets.GH_TOKEN }}
          git config --global pull.rebase false
          git pull remote ${{github.event.pull_request.head.ref}}
          git checkout -b ${{github.event.pull_request.head.ref}}

          yarn
          git add -A
          if [[ ! -z $(git status -s) ]] ; then
            git commit -m "chore(yarn): update yarn offline mirror"
            git push origin ${{ github.head_ref }}
          fi
