name: percy-update-base

on:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: percy-update-base-${{ github.ref }}
  cancel-in-progress: true

jobs:
  percy:
    # Prevent on forks because they don't have access to the secrets
    if: github.repository == 'carbon-design-system/carbon-web-components'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Build
        run: yarn build
      - name: Set env vars
        run: echo "PERCY_TOKEN=${{ secrets.PERCY_TOKEN }}" >> .env
      - name: Run percy-storybook
        run: yarn build-storybook && yarn percy-storybook --widths=320,1280
